---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-tester

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dns-tester
  namespace: dns-tester
  labels:
    app.kubernetes.io/name: dns-tester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dns-tester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dns-tester
    spec:
      # tolerations:
      # # these tolerations are to have the daemonset runnable on control plane nodes
      # # remove them if your control plane nodes should not run pods
      # - key: node-role.kubernetes.io/control-plane
      #   operator: Exists
      #   effect: NoSchedule
      # - key: node-role.kubernetes.io/master
      #   operator: Exi
      #   effect: NoSchedule
      containers:
      - name: tester
        image: fjramons/dns-tester:0.1
        env:
          - name: DESTINATION
            value: google.com
          - name: INTERVAL
            value: "1"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
